export const AIRLINES = [
  { code: 'BG', name: 'Biman Bangladesh Airlines' },
  { code: 'BS', name: 'US-Bangla Airlines' },
  { code: 'S2', name: 'Air Astra' },
  { code: 'EK', name: 'Emirates' },
  { code: 'QR', name: 'Qatar Airways' },
  { code: 'EY', name: 'Etihad Airways' },
  { code: 'SV', name: 'Saudia' },
  { code: 'GF', name: 'Gulf Air' },
  { code: 'WY', name: 'Oman Air' },
  { code: 'FZ', name: 'Flydubai' },
  { code: 'G9', name: 'Air Arabia' },
  { code: 'J9', name: 'Jazeera Airways' },
  { code: 'NX', name: 'Air Macau' },
  { code: 'SQ', name: 'Singapore Airlines' },
  { code: 'MH', name: 'Malaysia Airlines' },
  { code: 'TG', name: 'Thai Airways' },
  { code: 'GA', name: 'Garuda Indonesia' },
  { code: 'AI', name: 'Air India' },
  { code: 'UK', name: 'Vistara' },
  { code: 'SL', name: 'Thai Lion Air' },
  { code: '6E', name: 'IndiGo' },
  { code: 'AK', name: 'AirAsia' },
  { code: 'FD', name: 'Thai AirAsia' },
  { code: 'QZ', name: 'AirAsia Indonesia' },
  { code: 'D7', name: 'AirAsia X' },
  { code: 'TR', name: 'Scoot' },
  { code: 'OD', name: 'Batik Air Malaysia' },
  { code: 'MV', name: 'Air Mediterranean' },
  { code: 'UL', name: 'SriLankan Airlines' },
  { code: 'UB', name: 'Myanmar National Airlines' },
  { code: 'H9', name: 'Himalaya Airlines' },
  { code: 'RA', name: 'Nepal Airlines' },
  { code: 'IT', name: 'Tigerair Taiwan' },
  { code: 'CI', name: 'China Airlines' },
  { code: 'CX', name: 'Cathay Pacific' },
  { code: 'KA', name: 'Cathay Dragon' },
  { code: 'CA', name: 'Air China' },
  { code: 'CZ', name: 'China Southern Airlines' },
  { code: 'MU', name: 'China Eastern Airlines' },
  { code: 'HU', name: 'Hainan Airlines' },
  { code: 'KE', name: 'Korean Air' },
  { code: 'OZ', name: 'Asiana Airlines' },
  { code: 'NH', name: 'All Nippon Airways' },
  { code: 'JL', name: 'Japan Airlines' },
  { code: 'TK', name: 'Turkish Airlines' },
  { code: 'LH', name: 'Lufthansa' },
  { code: 'BA', name: 'British Airways' },
  { code: 'AF', name: 'Air France' },
  { code: 'KL', name: 'KLM Royal Dutch Airlines' },
  { code: 'AZ', name: 'ITA Airways' },
  { code: 'SK', name: 'Scandinavian Airlines' },
  { code: 'LX', name: 'Swiss International Air Lines' },
  { code: 'OS', name: 'Austrian Airlines' },
  { code: 'SN', name: 'Brussels Airlines' },
  { code: 'TP', name: 'TAP Air Portugal' },
  { code: 'IB', name: 'Iberia' },
  { code: 'VY', name: 'Vueling Airlines' },
  { code: 'U2', name: 'easyJet' },
  { code: 'FR', name: 'Ryanair' },
  { code: 'W6', name: 'Wizz Air' },
  { code: 'AA', name: 'American Airlines' },
  { code: 'UA', name: 'United Airlines' },
  { code: 'DL', name: 'Delta Air Lines' },
  { code: 'WN', name: 'Southwest Airlines' },
  { code: 'AC', name: 'Air Canada' },
  { code: 'QF', name: 'Qantas' },
  { code: 'NZ', name: 'Air New Zealand' },
  { code: 'ET', name: 'Ethiopian Airlines' },
  { code: 'MS', name: 'EgyptAir' },
  { code: 'RB', name: 'Syrian Arab Airlines' },
  { code: 'RJ', name: 'Royal Jordanian' },
  { code: 'ME', name: 'Middle East Airlines' },
  { code: 'KU', name: 'Kuwait Airways' },
  { code: 'IR', name: 'Iran Air' },
  { code: 'PK', name: 'Pakistan International Airlines' },
  { code: 'PA', name: 'Airblue' },
  { code: 'TM', name: 'LAM Mozambique Airlines' },
  { code: 'KC', name: 'Air Astana' },
  { code: 'HY', name: 'Uzbekistan Airways' },
  { code: 'T5', name: 'Turkmenistan Airlines' },
  { code: 'OV', name: 'SCAT Airlines' },
  { code: 'S7', name: 'S7 Airlines' },
  { code: 'SU', name: 'Aeroflot' },
  { code: 'PS', name: 'Ukraine International Airlines' },
  { code: 'LO', name: 'LOT Polish Airlines' },
  { code: 'OK', name: 'Czech Airlines' },
  { code: 'RO', name: 'TAROM' },
  { code: 'FB', name: 'Bulgaria Air' },
  { code: 'A3', name: 'Aegean Airlines' },
  { code: 'OA', name: 'Olympic Air' },
  { code: 'VN', name: 'Vietnam Airlines' },
  { code: 'VJ', name: 'VietJet Air' },
  { code: 'BL', name: 'Jetstar Pacific' },
  { code: 'QH', name: 'Bamboo Airways' },
  { code: 'PR', name: 'Philippine Airlines' },
  { code: 'Z2', name: 'Philippines AirAsia' },
  { code: 'CEB', name: 'Cebu Pacific' },
  { code: 'SJ', name: 'Sriwijaya Air' },
  { code: 'JT', name: 'Lion Air' },
  { code: 'ID', name: 'Batik Air Indonesia' },
  { code: 'BI', name: 'Royal Brunei Airlines' },
  { code: 'MI', name: 'SilkAir' },
  { code: 'XY', name: 'flynas' },
  { code: 'F3', name: 'Flyadeal' },
  { code: 'WB', name: 'RwandAir' },
  { code: 'AT', name: 'Royal Air Maroc' },
  { code: 'TU', name: 'Tunisair' },
  { code: 'AH', name: 'Air Algerie' },
  { code: 'KQ', name: 'Kenya Airways' },
  { code: 'SA', name: 'South African Airways' },
  { code: 'TC', name: 'Air Tanzania' },
  { code: 'OP', name: 'Chalk Airlines' },
  { code: 'GH', name: 'Globus' },
  { code: 'LM', name: 'Loganair' },
  { code: 'PC', name: 'Pegasus Airlines' },
  { code: 'XQ', name: 'SunExpress' },
  { code: 'TF', name: 'Braathens Regional' },
  { code: 'DY', name: 'Norwegian Air Shuttle' },
  { code: 'D8', name: 'Norwegian Air International' },
  { code: 'WF', name: 'Wideroe' },
  { code: 'AY', name: 'Finnair' },
  { code: 'BT', name: 'airBaltic' },
  { code: 'OU', name: 'Croatia Airlines' },
  { code: 'JP', name: 'Adria Airways' },
  { code: 'JU', name: 'Air Serbia' },
  { code: 'YM', name: 'Montenegro Airlines' },
  { code: 'GQ', name: 'Sky Express' },
  { code: 'ZB', name: 'Monarch Airlines' },
  { code: 'LS', name: 'Jet2' },
  { code: 'BY', name: 'TUI Airways' },
  { code: 'MT', name: 'Thomas Cook Airlines' },
  { code: 'TCX', name: 'Thomas Cook Airlines Scandinavia' },
  { code: 'HV', name: 'Transavia' },
  { code: 'TO', name: 'Transavia France' },
  { code: 'V7', name: 'Volotea' },
  { code: 'ZI', name: 'Aigle Azur' },
  { code: 'UU', name: 'Air Austral' },
  { code: 'SS', name: 'Corsair International' },
  { code: 'BJ', name: 'Nouvelair' },
  { code: 'XK', name: 'Air Corsica' },
  { code: 'A5', name: 'HOP!' },
  { code: 'ZH', name: 'Shenzhen Airlines' },
  { code: 'SC', name: 'Shandong Airlines' },
  { code: 'EU', name: 'Chengdu Airlines' },
  { code: '9C', name: 'Spring Airlines' },
  { code: 'GJ', name: 'Juneyao Airlines' },
  { code: 'HO', name: 'Juneyao Air' },
  { code: 'G5', name: 'China Express Airlines' },
  { code: 'NS', name: 'Hebei Airlines' },
  { code: 'PN', name: 'West Air China' },
  { code: 'Y8', name: 'Suparna Airlines' },
  { code: 'TV', name: 'Tibet Airlines' },
  { code: 'GS', name: 'Tianjin Airlines' },
  { code: 'CN', name: 'Grand China Air' },
  { code: 'IO', name: 'IrAero' },
  { code: 'N4', name: 'Nordwind Airlines' },
  { code: 'UT', name: 'UTair Aviation' },
  { code: 'U6', name: 'Ural Airlines' },
  { code: 'R3', name: 'Yakutia Airlines' },
  { code: 'FV', name: 'Rossiya Airlines' },
  { code: 'DP', name: 'Pobeda' },
  { code: '5N', name: 'Smartavia' },
  { code: 'LJ', name: 'Jin Air' },
  { code: 'TW', name: "T'way Air" },
  { code: 'ZE', name: 'Eastar Jet' },
  { code: 'BX', name: 'Air Busan' },
  { code: 'RS', name: 'Air Seoul' },
  { code: 'MM', name: 'Peach Aviation' },
  { code: 'GK', name: 'Jetstar Japan' },
  { code: 'BC', name: 'Skymark Airlines' },
  { code: 'HD', name: 'Air Do' },
  { code: 'SFJ', name: 'Starflyer' },
  { code: 'NU', name: 'Japan Transocean Air' },
  { code: 'EG', name: 'Japan Asia Airways' },
  { code: 'IV', name: 'Wind Jet' },
  { code: 'N7', name: 'Nordic Regional Airlines' },
  { code: 'OG', name: 'PLAY' },
  { code: 'FI', name: 'Icelandair' },
  { code: 'EI', name: 'Aer Lingus' },
  { code: 'RE', name: 'Stobart Air' },
  { code: 'WX', name: 'CityJet' },
  { code: 'ZT', name: 'Titan Airways' },
  { code: 'T3', name: 'Eastern Airways' },
  { code: 'BE', name: 'Flybe' },
  { code: 'OW', name: 'Skywest Airlines Australia' },
  { code: 'JQ', name: 'Jetstar Airways' },
  { code: 'WE', name: 'Thai Smile' },
  { code: 'DD', name: 'Nok Air' },
  { code: 'PG', name: 'Bangkok Airways' },
  { code: 'FW', name: 'Ibex Airlines' },
  { code: 'K6', name: 'Cambodia Angkor Air' },
  { code: 'QV', name: 'Lao Airlines' },
  { code: 'UE', name: 'Ultimate Air' },
  { code: 'YH', name: 'Yangon Airways' },
  { code: 'RAK', name: 'Rakhine National Airlines' },
  { code: 'MA', name: 'Malev Hungarian Airlines' },
  { code: 'W2', name: 'Flexflight' },
  { code: 'LT', name: 'LTU International' },
  { code: 'CFG', name: 'Condor' },
  { code: 'DE', name: 'Condor' },
  { code: 'X3', name: 'TUI fly Deutschland' },
  { code: 'HF', name: 'Hapagfly' },
  { code: 'AG', name: 'Aruba Airlines' },
  { code: 'CM', name: 'Copa Airlines' },
  { code: 'AV', name: 'Avianca' },
  { code: 'LA', name: 'LATAM Airlines' },
  { code: 'G3', name: 'Gol Transportes Aereos' },
  { code: 'AD', name: 'Azul Brazilian Airlines' },
  { code: 'JJ', name: 'LATAM Brasil' },
  { code: 'AR', name: 'Aerolineas Argentinas' },
  { code: 'AM', name: 'Aeromexico' },
  { code: 'MX', name: 'Mexicana de Aviacion' },
  { code: 'Y4', name: 'Volaris' },
  { code: 'VB', name: 'VivaAerobus' },
  { code: '4O', name: 'Interjet' },
  { code: 'WS', name: 'WestJet' },
  { code: 'PD', name: 'Porter Airlines' },
  { code: 'F8', name: 'Flair Airlines' },
  { code: 'WJ', name: 'Air Labrador' },
  { code: 'ZX', name: 'Air Georgian' },
  { code: 'WR', name: 'WestJet Encore' },
  { code: 'B6', name: 'JetBlue Airways' },
  { code: 'AS', name: 'Alaska Airlines' },
  { code: 'F9', name: 'Frontier Airlines' },
  { code: 'NK', name: 'Spirit Airlines' },
  { code: 'G4', name: 'Allegiant Air' },
  { code: 'SY', name: 'Sun Country Airlines' },
  { code: 'HA', name: 'Hawaiian Airlines' },
  { code: 'OO', name: 'SkyWest Airlines' },
  { code: 'YX', name: 'Republic Airways' },
  { code: 'OH', name: 'PSA Airlines' },
  { code: 'MQ', name: 'Envoy Air' },
  { code: 'EV', name: 'ExpressJet Airlines' },
  { code: 'GD', name: 'Jazeera Airways' },
  { code: 'SF', name: 'Tassili Airlines' },
  { code: 'HC', name: 'Air Senegal' },
  { code: 'QU', name: 'UTair Ukraine' },
  { code: 'SP', name: 'SATA Air Acores' },
  { code: 'NI', name: 'Portugalia' },
  { code: 'YW', name: 'Air Nostrum' },
  { code: 'NT', name: 'Binter Canarias' },
  { code: 'PM', name: 'Canaryfly' },
  { code: 'UX', name: 'Air Europa' },
  { code: 'I2', name: 'Iberia Express' },
  { code: 'V6', name: 'VistaJet' },
]
